
language: node_js
node_js:
  - "10"
  - "13"
deploy:
  provider: npm
  email: "594404963@qq.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    branch: master
jobs:
  include:
    - 
      stage: Produce Coverage
      node_js: "13"
      script: npm run coveralls
