//===========================================================================
// 
// Simple Hero Siege
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Map Author: Pump,ArcadeKid,HelpfulPug
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // User-defined
    integer array           udg_Heroes
    integer array           udg_UnitEnemy
    integer array           udg_UnitAlly
    integer                 udg_CreepLevel             = 0
    rect array              udg_AttackRandomizer
    real                    udg_BreakCountReal         = 0
    real                    udg_JungleFarmCounter      = 0
    unit array              udg_TheShops
    itemtype                udg_ItemsBasic             = null
    integer                 udg_EliteMercs             = 0
    real                    udg_BossSpawnCount         = 0
    integer                 udg_RoundCounter           = 0
    integer                 udg_RuneDropCount          = 0
    integer array           udg_RuneDropType
    timer                   udg_RestartTimer           = null
    integer array           udg_CityCreepType
    integer array           udg_ShrineCreepType
    integer array           udg_GroundsCreepType
    integer array           udg_JailCreepType

    // Generated
    rect                    gg_rct_SouthAttack         = null
    rect                    gg_rct_WestAttack          = null
    rect                    gg_rct_NorthAttack         = null
    rect                    gg_rct_EastAttack          = null
    rect                    gg_rct_TheMiddle           = null
    rect                    gg_rct_Jail_6              = null
    rect                    gg_rct_Jail5               = null
    rect                    gg_rct_Jail1               = null
    rect                    gg_rct_Shrine3             = null
    rect                    gg_rct_Shrine1             = null
    rect                    gg_rct_Shrine2             = null
    rect                    gg_rct_Grounds3            = null
    rect                    gg_rct_Grounds1            = null
    rect                    gg_rct_Grounds2            = null
    rect                    gg_rct_City_2              = null
    rect                    gg_rct_City_3              = null
    rect                    gg_rct_City_4              = null
    rect                    gg_rct_City_Weak_1         = null
    rect                    gg_rct_City_6              = null
    rect                    gg_rct_City_5              = null
    rect                    gg_rct_City_Weak_3         = null
    rect                    gg_rct_City_Weak_2         = null
    rect                    gg_rct_Hero_Select         = null
    rect                    gg_rct_ShrineWeak1         = null
    rect                    gg_rct_ShrineWeak2         = null
    rect                    gg_rct_ShrineWeak3         = null
    rect                    gg_rct_ShrineWeak5         = null
    rect                    gg_rct_ShrineWeak4         = null
    rect                    gg_rct_ShrineWeak6         = null
    rect                    gg_rct_Grounds4            = null
    rect                    gg_rct_Grounds5            = null
    rect                    gg_rct_Jail2               = null
    rect                    gg_rct_Jail3               = null
    rect                    gg_rct_Jail4               = null
    rect                    gg_rct_Jail7               = null
    rect                    gg_rct_GroundsWeather      = null
    rect                    gg_rct_CityWeather         = null
    rect                    gg_rct_DungeonWeather      = null
    trigger                 gg_trg_Melee_Initialization = null
    trigger                 gg_trg_LOSERS              = null
    trigger                 gg_trg_SetUnits            = null
    trigger                 gg_trg_Player_Startup      = null
    trigger                 gg_trg_Hero_Select         = null
    trigger                 gg_trg_Hero_Random         = null
    trigger                 gg_trg_Set_Up_Over         = null
    trigger                 gg_trg_ATTACK              = null
    trigger                 gg_trg_Boss_ATTACK         = null
    trigger                 gg_trg_ATTACKSend          = null
    trigger                 gg_trg_Creep_Level_Up      = null
    trigger                 gg_trg_Items               = null
    trigger                 gg_trg_Break_Counter       = null
    trigger                 gg_trg_Take_A_Break        = null
    trigger                 gg_trg_Back_to_Fight       = null
    trigger                 gg_trg_Set_Creep_Types     = null
    trigger                 gg_trg_Set_Item_Drops      = null
    trigger                 gg_trg_Make_Creeps_Startup = null
    trigger                 gg_trg_Drop_Item           = null
    trigger                 gg_trg_Camp_Respawn        = null
    trigger                 gg_trg_Jungle_Farm_Counter = null
    trigger                 gg_trg_Team_Farm_Creeps    = null
    trigger                 gg_trg_Jail1               = null
    trigger                 gg_trg_Jail2               = null
    trigger                 gg_trg_Jail3               = null
    trigger                 gg_trg_Jail4               = null
    trigger                 gg_trg_Jail5               = null
    trigger                 gg_trg_Jail7               = null
    trigger                 gg_trg_Jail6               = null
    trigger                 gg_trg_Grounds1            = null
    trigger                 gg_trg_Grounds2            = null
    trigger                 gg_trg_Grounds3            = null
    trigger                 gg_trg_Grounds4            = null
    trigger                 gg_trg_Grounds5            = null
    trigger                 gg_trg_Shrine3             = null
    trigger                 gg_trg_Shrine2             = null
    trigger                 gg_trg_Shrine1             = null
    trigger                 gg_trg_ShrineWeak1         = null
    trigger                 gg_trg_ShrineWeak2         = null
    trigger                 gg_trg_ShrineWeak3         = null
    trigger                 gg_trg_ShrineWeak4         = null
    trigger                 gg_trg_ShrineWeak5         = null
    trigger                 gg_trg_ShrineWeak6         = null
    trigger                 gg_trg_City_Weak_3         = null
    trigger                 gg_trg_City_Weak_2         = null
    trigger                 gg_trg_City_Weak_1         = null
    trigger                 gg_trg_City_6              = null
    trigger                 gg_trg_City_5              = null
    trigger                 gg_trg_City_4              = null
    trigger                 gg_trg_City_3              = null
    trigger                 gg_trg_City_2              = null
    trigger                 gg_trg_Show_Me_Number      = null
    trigger                 gg_trg_Help_Me             = null
    trigger                 gg_trg_Send_Dudes          = null
    unit                    gg_unit_h000_0007          = null
    unit                    gg_unit_nmrk_0004          = null
    unit                    gg_unit_nmrk_0005          = null
endglobals

function InitGlobals takes nothing returns nothing
    local integer i = 0
    set udg_CreepLevel = 2
    set udg_BreakCountReal = 0
    set udg_JungleFarmCounter = 0
    set udg_EliteMercs = 0
    set udg_BossSpawnCount = 0
    set udg_RoundCounter = 0
    set udg_RuneDropCount = 0
    set udg_RestartTimer = CreateTimer()
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateBuildingsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n004', 768.0, -1664.0, 270.000, 'n004' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = BlzCreateUnitWithSkin( p, 'h001', 1184.0, -1248.0, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h005', 1152.0, -1664.0, 270.000, 'h005' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer1 takes nothing returns nothing
    local player p = Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', 800.0, 672.0, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'n004', 1152.0, 320.0, 270.000, 'n004' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = BlzCreateUnitWithSkin( p, 'h005', 1216.0, 704.0, 270.000, 'h005' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer2 takes nothing returns nothing
    local player p = Player(2)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'h001', -800.0, 672.0, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'n004', -1152.0, 320.0, 270.000, 'n004' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = BlzCreateUnitWithSkin( p, 'h005', -1216.0, 704.0, 270.000, 'h005' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer3 takes nothing returns nothing
    local player p = Player(3)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'n004', -832.0, -1664.0, 270.000, 'n004' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = BlzCreateUnitWithSkin( p, 'h001', -1184.0, -1312.0, 270.000, 'h001' )
    set u = BlzCreateUnitWithSkin( p, 'h005', -1216.0, -1728.0, 270.000, 'h005' )
endfunction

//===========================================================================
function CreateBuildingsForPlayer23 takes nothing returns nothing
    local player p = Player(23)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set gg_unit_h000_0007 = BlzCreateUnitWithSkin( p, 'h000', 0.0, -512.0, 270.000, 'h000' )
endfunction

//===========================================================================
function CreateNeutralPassiveBuildings takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set gg_unit_nmrk_0004 = BlzCreateUnitWithSkin( p, 'nmrk', 512.0, 0.0, 270.000, 'nmrk' )
    call SetUnitColor( gg_unit_nmrk_0004, ConvertPlayerColor(0) )
    set gg_unit_nmrk_0005 = BlzCreateUnitWithSkin( p, 'nmrk', -512.0, -1024.0, 270.000, 'nmrk' )
    call SetUnitColor( gg_unit_nmrk_0005, ConvertPlayerColor(0) )
    set u = BlzCreateUnitWithSkin( p, 'h002', 64.0, -7488.0, 270.000, 'h002' )
    set u = BlzCreateUnitWithSkin( p, 'n001', 1088.0, -7552.0, 270.000, 'n001' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
    set u = BlzCreateUnitWithSkin( p, 'n000', 640.0, -7808.0, 270.000, 'n000' )
    call SetUnitColor( u, ConvertPlayerColor(0) )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer0(  )
    call CreateBuildingsForPlayer1(  )
    call CreateBuildingsForPlayer2(  )
    call CreateBuildingsForPlayer3(  )
    call CreateBuildingsForPlayer23(  )
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreateNeutralPassiveBuildings(  )
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************

function CreateRegions takes nothing returns nothing
    local weathereffect we

    set gg_rct_SouthAttack = Rect( -544.0, -6560.0, 544.0, -6112.0 )
    set gg_rct_WestAttack = Rect( -6976.0, -864.0, -6592.0, -96.0 )
    set gg_rct_NorthAttack = Rect( -512.0, 6528.0, 672.0, 6880.0 )
    set gg_rct_EastAttack = Rect( 6720.0, -960.0, 7136.0, -64.0 )
    set gg_rct_TheMiddle = Rect( -1024.0, -1600.0, 992.0, 544.0 )
    set gg_rct_Jail_6 = Rect( 5408.0, -3904.0, 6976.0, -3392.0 )
    set gg_rct_Jail5 = Rect( 4160.0, -3424.0, 4512.0, -3040.0 )
    set gg_rct_Jail1 = Rect( 2400.0, -4384.0, 2848.0, -4000.0 )
    set gg_rct_Shrine3 = Rect( 5152.0, 3808.0, 5792.0, 4320.0 )
    set gg_rct_Shrine1 = Rect( 4480.0, 6208.0, 5760.0, 6912.0 )
    set we = AddWeatherEffect( gg_rct_Shrine1, 'LRaa' )
    call EnableWeatherEffect( we, true )
    set gg_rct_Shrine2 = Rect( 4384.0, 5024.0, 5024.0, 5536.0 )
    set gg_rct_Grounds3 = Rect( -3072.0, 6464.0, -2432.0, 6976.0 )
    set gg_rct_Grounds1 = Rect( -7040.0, 6496.0, -6400.0, 7008.0 )
    set gg_rct_Grounds2 = Rect( -6752.0, 2944.0, -6208.0, 3552.0 )
    set gg_rct_City_2 = Rect( -7552.0, -3232.0, -6912.0, -2720.0 )
    set gg_rct_City_3 = Rect( -5056.0, -5088.0, -4416.0, -4576.0 )
    set gg_rct_City_4 = Rect( -3616.0, -7328.0, -2976.0, -6816.0 )
    set gg_rct_City_Weak_1 = Rect( -3584.0, -3488.0, -3168.0, -3040.0 )
    set gg_rct_City_6 = Rect( -6592.0, -6784.0, -5952.0, -6272.0 )
    set gg_rct_City_5 = Rect( -6720.0, -5120.0, -6080.0, -4480.0 )
    set gg_rct_City_Weak_3 = Rect( -4928.0, -3520.0, -4512.0, -3072.0 )
    set gg_rct_City_Weak_2 = Rect( -3200.0, -5088.0, -2784.0, -4640.0 )
    set gg_rct_Hero_Select = Rect( -1056.0, -7936.0, 1280.0, -7392.0 )
    set gg_rct_ShrineWeak1 = Rect( 2432.0, 7168.0, 3072.0, 7680.0 )
    set gg_rct_ShrineWeak2 = Rect( 1728.0, 4864.0, 2368.0, 5376.0 )
    set gg_rct_ShrineWeak3 = Rect( 5600.0, 1248.0, 6240.0, 1760.0 )
    set gg_rct_ShrineWeak5 = Rect( 7136.0, 6720.0, 7776.0, 7232.0 )
    set gg_rct_ShrineWeak4 = Rect( 7008.0, 3424.0, 7648.0, 3936.0 )
    set gg_rct_ShrineWeak6 = Rect( 3520.0, 2016.0, 4160.0, 2528.0 )
    set gg_rct_Grounds4 = Rect( -5664.0, 4128.0, -4544.0, 5152.0 )
    set gg_rct_Grounds5 = Rect( -3840.0, 2752.0, -3200.0, 3264.0 )
    set gg_rct_Jail2 = Rect( 2336.0, -5472.0, 2784.0, -5088.0 )
    set gg_rct_Jail3 = Rect( 4224.0, -7040.0, 4672.0, -6656.0 )
    set gg_rct_Jail4 = Rect( 6816.0, -7040.0, 7264.0, -6656.0 )
    set gg_rct_Jail7 = Rect( 4704.0, -5504.0, 5152.0, -5120.0 )
    set gg_rct_GroundsWeather = Rect( -7456.0, 1408.0, -1728.0, 7648.0 )
    set we = AddWeatherEffect( gg_rct_GroundsWeather, 'RAlr' )
    call EnableWeatherEffect( we, true )
    set gg_rct_CityWeather = Rect( -8032.0, -3968.0, -6176.0, -2272.0 )
    set we = AddWeatherEffect( gg_rct_CityWeather, 'LRma' )
    call EnableWeatherEffect( we, true )
    set gg_rct_DungeonWeather = Rect( 1888.0, -7744.0, 7712.0, -2976.0 )
    set we = AddWeatherEffect( gg_rct_DungeonWeather, 'FDbl' )
    call EnableWeatherEffect( we, true )
endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Melee Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Melee_Initialization_Func006A takes nothing returns nothing
    call CreateFogModifierRectBJ( true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_TheMiddle )
    call SetPlayerStateBJ( GetEnumPlayer(), PLAYER_STATE_RESOURCE_HERO_TOKENS, 1 )
    call SetPlayerStateBJ( GetEnumPlayer(), PLAYER_STATE_RESOURCE_GOLD, 350 )
    call SetPlayerStateBJ( GetEnumPlayer(), PLAYER_STATE_RESOURCE_LUMBER, 150 )
endfunction

function Trig_Melee_Initialization_Actions takes nothing returns nothing
    call MeleeStartingVisibility(  )
    call MeleeStartingAI(  )
    call CreateQuestBJ( bj_QUESTTYPE_REQ_DISCOVERED, "TRIGSTR_022", "TRIGSTR_023", "ReplaceableTextures\\CommandButtons\\BTNSpellBookBLS.blp" )
    call CreateQuestBJ( bj_QUESTTYPE_OPT_DISCOVERED, "TRIGSTR_024", "TRIGSTR_025", "ReplaceableTextures\\CommandButtons\\BTNSpellBookBLS.blp" )
    call ForForce( GetPlayersAll(), function Trig_Melee_Initialization_Func006A )
endfunction

//===========================================================================
function InitTrig_Melee_Initialization takes nothing returns nothing
    set gg_trg_Melee_Initialization = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions )
endfunction

//===========================================================================
// Trigger: LOSERS
//===========================================================================
function Trig_LOSERS_Func001A takes nothing returns nothing
    call CustomDefeatBJ( GetEnumPlayer(), "TRIGSTR_677" )
endfunction

function Trig_LOSERS_Actions takes nothing returns nothing
    call ForForce( GetPlayersAllies(Player(0)), function Trig_LOSERS_Func001A )
endfunction

//===========================================================================
function InitTrig_LOSERS takes nothing returns nothing
    set gg_trg_LOSERS = CreateTrigger(  )
    call TriggerRegisterUnitEvent( gg_trg_LOSERS, gg_unit_h000_0007, EVENT_UNIT_DEATH )
    call TriggerAddAction( gg_trg_LOSERS, function Trig_LOSERS_Actions )
endfunction

//===========================================================================
// Trigger: SetUnits
//===========================================================================
function Trig_SetUnits_Actions takes nothing returns nothing
    // Shops
    set udg_TheShops[1] = gg_unit_nmrk_0005
    set udg_TheShops[2] = gg_unit_nmrk_0004
    // Heroes
    set udg_Heroes[1] = 'Hpal'
    set udg_Heroes[2] = 'Hamg'
    set udg_Heroes[3] = 'Hmkg'
    set udg_Heroes[4] = 'Hblm'
    set udg_Heroes[5] = 'Obla'
    set udg_Heroes[6] = 'Ofar'
    set udg_Heroes[7] = 'Otch'
    set udg_Heroes[8] = 'Oshd'
    set udg_Heroes[9] = 'Udea'
    set udg_Heroes[10] = 'Ulic'
    set udg_Heroes[11] = 'Udre'
    set udg_Heroes[12] = 'Ucrl'
    set udg_Heroes[13] = 'Ekee'
    set udg_Heroes[14] = 'Emoo'
    set udg_Heroes[15] = 'Edem'
    set udg_Heroes[16] = 'Ewar'
    set udg_Heroes[17] = 'Nalc'
    set udg_Heroes[18] = 'Nngs'
    set udg_Heroes[19] = 'Hamg'
    set udg_Heroes[20] = 'Nbst'
    set udg_Heroes[21] = 'Npbm'
    set udg_Heroes[22] = 'Nbrn'
    set udg_Heroes[23] = 'Nfir'
    set udg_Heroes[24] = 'Nplh'
    set udg_Heroes[25] = 'U000'
    // AllyUnits
    set udg_AttackRandomizer[1] = gg_rct_SouthAttack
    set udg_AttackRandomizer[2] = gg_rct_WestAttack
    set udg_AttackRandomizer[3] = gg_rct_EastAttack
    set udg_AttackRandomizer[4] = gg_rct_NorthAttack
    set udg_UnitAlly[1] = 'hfoo'
    set udg_UnitAlly[2] = 'hrif'
    set udg_UnitAlly[3] = 'nhea'
    set udg_UnitAlly[4] = 'ogru'
    set udg_UnitAlly[5] = 'ohun'
    set udg_UnitAlly[6] = 'ugho'
    set udg_UnitAlly[7] = 'nska'
    set udg_UnitAlly[8] = 'earc'
    set udg_UnitAlly[9] = 'esen'
    set udg_UnitAlly[10] = 'hkni'
    set udg_UnitAlly[11] = 'hcth'
    set udg_UnitAlly[12] = 'otau'
    set udg_UnitAlly[13] = 'uabo'
    set udg_UnitAlly[14] = 'nwat'
    set udg_UnitAlly[15] = 'otbk'
endfunction

//===========================================================================
function InitTrig_SetUnits takes nothing returns nothing
    set gg_trg_SetUnits = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_SetUnits, 0.10 )
    call TriggerAddAction( gg_trg_SetUnits, function Trig_SetUnits_Actions )
endfunction

//===========================================================================
// Trigger: Player Startup
//===========================================================================
function Trig_Player_Startup_Func008A takes nothing returns nothing
    call SetPlayerAllianceStateBJ( GetEnumPlayer(), GetEnumPlayer(), bj_ALLIANCE_ALLIED_VISION )
    call SetPlayerAllianceStateBJ( GetEnumPlayer(), Player(22), bj_ALLIANCE_UNALLIED )
    call SetPlayerAllianceStateBJ( Player(22), GetEnumPlayer(), bj_ALLIANCE_UNALLIED )
    call SetPlayerAllianceStateBJ( Player(22), Player(23), bj_ALLIANCE_UNALLIED )
    call CreateNUnitsAtLoc( 1, 'e000', GetEnumPlayer(), GetRectCenter(gg_rct_Hero_Select), bj_UNIT_FACING )
    call CreateFogModifierRectBJ( true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_Hero_Select )
endfunction

function Trig_Player_Startup_Actions takes nothing returns nothing
    call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
    call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
    call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
    call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
    call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
    call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
    call EnableTrigger( gg_trg_Camp_Respawn )
    call ForForce( GetPlayersByMapControl(MAP_CONTROL_USER), function Trig_Player_Startup_Func008A )
endfunction

//===========================================================================
function InitTrig_Player_Startup takes nothing returns nothing
    set gg_trg_Player_Startup = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Player_Startup, 1.00 )
    call TriggerAddAction( gg_trg_Player_Startup, function Trig_Player_Startup_Actions )
endfunction

//===========================================================================
// Trigger: Hero Select
//===========================================================================
function Trig_Hero_Select_Conditions takes nothing returns boolean
    if ( not ( GetUnitTypeId(GetBuyingUnit()) == 'e000' ) ) then
        return false
    endif
    if ( not ( IsUnitType(GetSoldUnit(), UNIT_TYPE_HERO) == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Hero_Select_Actions takes nothing returns nothing
    call RemoveUnit( GetBuyingUnit() )
    call SetUnitPositionLoc( GetSoldUnit(), GetRectCenter(gg_rct_TheMiddle) )
endfunction

//===========================================================================
function InitTrig_Hero_Select takes nothing returns nothing
    set gg_trg_Hero_Select = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Hero_Select, EVENT_PLAYER_UNIT_SELL )
    call TriggerAddCondition( gg_trg_Hero_Select, Condition( function Trig_Hero_Select_Conditions ) )
    call TriggerAddAction( gg_trg_Hero_Select, function Trig_Hero_Select_Actions )
endfunction

//===========================================================================
// Trigger: Hero Random
//===========================================================================
function Trig_Hero_Random_Conditions takes nothing returns boolean
    if ( not ( GetUnitTypeId(GetBuyingUnit()) == 'e000' ) ) then
        return false
    endif
    if ( not ( GetUnitTypeId(GetSoldUnit()) == 'H003' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Hero_Random_Actions takes nothing returns nothing
    call RemoveUnit( GetBuyingUnit() )
    call CreateNUnitsAtLoc( 1, udg_Heroes[GetRandomInt(1, 25)], GetOwningPlayer(GetSoldUnit()), GetRectCenter(GetPlayableMapRect()), bj_UNIT_FACING )
    call RemoveUnit( GetSoldUnit() )
endfunction

//===========================================================================
function InitTrig_Hero_Random takes nothing returns nothing
    set gg_trg_Hero_Random = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Hero_Random, EVENT_PLAYER_UNIT_SELL )
    call TriggerAddCondition( gg_trg_Hero_Random, Condition( function Trig_Hero_Random_Conditions ) )
    call TriggerAddAction( gg_trg_Hero_Random, function Trig_Hero_Random_Actions )
endfunction

//===========================================================================
// Trigger: Set Up Over
//===========================================================================
function Trig_Set_Up_Over_Actions takes nothing returns nothing
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, "TRIGSTR_676" )
    call EnableTrigger( gg_trg_ATTACK )
    call DisableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Set_Up_Over takes nothing returns nothing
    set gg_trg_Set_Up_Over = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Set_Up_Over, 80.00 )
    call TriggerAddAction( gg_trg_Set_Up_Over, function Trig_Set_Up_Over_Actions )
endfunction

//===========================================================================
// Trigger: ATTACK
//===========================================================================
function Trig_ATTACK_Func001C takes nothing returns boolean
    if ( not ( udg_CreepLevel < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_ATTACK_Actions takes nothing returns nothing
    if ( Trig_ATTACK_Func001C() ) then
        call CreateNUnitsAtLoc( 3, ChooseRandomCreepBJ(GetRandomInt(1, udg_CreepLevel)), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
    else
        call CreateNUnitsAtLoc( 3, ChooseRandomCreepBJ(GetRandomInt(( udg_CreepLevel - 1 ), udg_CreepLevel)), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
    endif
endfunction

//===========================================================================
function InitTrig_ATTACK takes nothing returns nothing
    set gg_trg_ATTACK = CreateTrigger(  )
    call DisableTrigger( gg_trg_ATTACK )
    call TriggerRegisterPlayerChatEvent( gg_trg_ATTACK, Player(0), "GO NOW", true )
    call TriggerRegisterTimerEventPeriodic( gg_trg_ATTACK, 10.00 )
    call TriggerAddAction( gg_trg_ATTACK, function Trig_ATTACK_Actions )
endfunction

//===========================================================================
// Trigger: Boss ATTACK
//===========================================================================
function Trig_Boss_ATTACK_Func003C takes nothing returns boolean
    if ( not ( udg_CreepLevel < 8 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Boss_ATTACK_Actions takes nothing returns nothing
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, "TRIGSTR_507" )
    set udg_BossSpawnCount = 0.00
    if ( Trig_Boss_ATTACK_Func003C() ) then
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(( udg_CreepLevel + 2 )), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(( udg_CreepLevel + 2 )), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(( udg_CreepLevel + 2 )), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(( udg_CreepLevel + 2 )), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
    else
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(10), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(10), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(10), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
        call CreateNUnitsAtLoc( 1, ChooseRandomCreepBJ(10), Player(22), GetRectCenter(udg_AttackRandomizer[GetRandomInt(1, 4)]), bj_UNIT_FACING )
    endif
endfunction

//===========================================================================
function InitTrig_Boss_ATTACK takes nothing returns nothing
    set gg_trg_Boss_ATTACK = CreateTrigger(  )
    call TriggerRegisterVariableEvent( gg_trg_Boss_ATTACK, "udg_BossSpawnCount", EQUAL, 35.00 )
    call TriggerAddAction( gg_trg_Boss_ATTACK, function Trig_Boss_ATTACK_Actions )
endfunction

//===========================================================================
// Trigger: ATTACKSend
//===========================================================================
function Trig_ATTACKSend_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) == Player(22) ) ) then
        return false
    endif
    return true
endfunction

function Trig_ATTACKSend_Actions takes nothing returns nothing
    call IssuePointOrderLocBJ( GetTriggerUnit(), "attack", GetUnitLoc(gg_unit_h000_0007) )
endfunction

//===========================================================================
function InitTrig_ATTACKSend takes nothing returns nothing
    set gg_trg_ATTACKSend = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_ATTACKSend, gg_rct_WestAttack )
    call TriggerRegisterEnterRectSimple( gg_trg_ATTACKSend, gg_rct_SouthAttack )
    call TriggerRegisterEnterRectSimple( gg_trg_ATTACKSend, gg_rct_EastAttack )
    call TriggerRegisterEnterRectSimple( gg_trg_ATTACKSend, gg_rct_NorthAttack )
    call TriggerAddCondition( gg_trg_ATTACKSend, Condition( function Trig_ATTACKSend_Conditions ) )
    call TriggerAddAction( gg_trg_ATTACKSend, function Trig_ATTACKSend_Actions )
endfunction

//===========================================================================
// Trigger: Creep Level Up
//===========================================================================
function Trig_Creep_Level_Up_Conditions takes nothing returns boolean
    if ( not ( IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Creep_Level_Up_Func001C takes nothing returns boolean
    if ( not ( udg_CreepLevel < GetHeroLevel(GetTriggerUnit()) ) ) then
        return false
    endif
    if ( not ( udg_CreepLevel < 11 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Creep_Level_Up_Actions takes nothing returns nothing
    if ( Trig_Creep_Level_Up_Func001C() ) then
        set udg_CreepLevel = GetHeroLevel(GetTriggerUnit())
    else
        call DoNothing(  )
    endif
endfunction

//===========================================================================
function InitTrig_Creep_Level_Up takes nothing returns nothing
    set gg_trg_Creep_Level_Up = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Creep_Level_Up, EVENT_PLAYER_HERO_LEVEL )
    call TriggerAddCondition( gg_trg_Creep_Level_Up, Condition( function Trig_Creep_Level_Up_Conditions ) )
    call TriggerAddAction( gg_trg_Creep_Level_Up, function Trig_Creep_Level_Up_Actions )
endfunction

//===========================================================================
// Trigger: Items
//===========================================================================
function Trig_Items_Func001C takes nothing returns boolean
    if ( not ( udg_CreepLevel < 6 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Items_Actions takes nothing returns nothing
    if ( Trig_Items_Func001C() ) then
        call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[1], 1, 1 )
        call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[2], 1, 1 )
        call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(1, ( udg_CreepLevel + 2 )), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
        call DisableTrigger( GetTriggeringTrigger() )
    else
        call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(3, udg_CreepLevel), ITEM_TYPE_ANY), udg_TheShops[1], 1, 1 )
        call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(3, udg_CreepLevel), ITEM_TYPE_ANY), udg_TheShops[2], 1, 1 )
        call AddItemToStockBJ( ChooseRandomItemExBJ(GetRandomInt(3, udg_CreepLevel), ITEM_TYPE_ANY), udg_TheShops[GetRandomInt(1, 2)], 1, 1 )
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Items takes nothing returns nothing
    set gg_trg_Items = CreateTrigger(  )
    call DisableTrigger( gg_trg_Items )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Items, 1.00 )
    call TriggerAddAction( gg_trg_Items, function Trig_Items_Actions )
endfunction

//===========================================================================
// Trigger: Break Counter
//===========================================================================
function Trig_Break_Counter_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) == Player(22) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Break_Counter_Actions takes nothing returns nothing
    set udg_BreakCountReal = ( udg_BreakCountReal + 1 )
    set udg_BossSpawnCount = ( udg_BossSpawnCount + 1 )
endfunction

//===========================================================================
function InitTrig_Break_Counter takes nothing returns nothing
    set gg_trg_Break_Counter = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Break_Counter, EVENT_PLAYER_UNIT_DEATH )
    call TriggerAddCondition( gg_trg_Break_Counter, Condition( function Trig_Break_Counter_Conditions ) )
    call TriggerAddAction( gg_trg_Break_Counter, function Trig_Break_Counter_Actions )
endfunction

//===========================================================================
// Trigger: Take A Break
//===========================================================================
function Trig_Take_A_Break_Func005A takes nothing returns nothing
    call AdjustPlayerStateBJ( 150, GetEnumPlayer(), PLAYER_STATE_RESOURCE_GOLD )
    call AdjustPlayerStateBJ( 50, GetEnumPlayer(), PLAYER_STATE_RESOURCE_LUMBER )
endfunction

function Trig_Take_A_Break_Actions takes nothing returns nothing
    set udg_RoundCounter = ( udg_RoundCounter + 1 )
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, "TRIGSTR_017" )
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, I2S(udg_RoundCounter) )
    set udg_EliteMercs = 3
    call ForForce( GetPlayersByMapControl(MAP_CONTROL_USER), function Trig_Take_A_Break_Func005A )
    call DisableTrigger( gg_trg_ATTACK )
    call DisableTrigger( gg_trg_Break_Counter )
    call DisableTrigger( gg_trg_ATTACKSend )
    call EnableTrigger( gg_trg_Items )
    call EnableTrigger( gg_trg_Camp_Respawn )
    set udg_BreakCountReal = 0.00
    call StartTimerBJ( udg_RestartTimer, false, 300.00 )
endfunction

//===========================================================================
function InitTrig_Take_A_Break takes nothing returns nothing
    set gg_trg_Take_A_Break = CreateTrigger(  )
    call TriggerRegisterVariableEvent( gg_trg_Take_A_Break, "udg_BreakCountReal", EQUAL, 55.00 )
    call TriggerAddAction( gg_trg_Take_A_Break, function Trig_Take_A_Break_Actions )
endfunction

//===========================================================================
// Trigger: Back to Fight
//===========================================================================
function Trig_Back_to_Fight_Actions takes nothing returns nothing
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, "TRIGSTR_018" )
    call EnableTrigger( gg_trg_ATTACK )
    call EnableTrigger( gg_trg_ATTACKSend )
    call EnableTrigger( gg_trg_Break_Counter )
endfunction

//===========================================================================
function InitTrig_Back_to_Fight takes nothing returns nothing
    set gg_trg_Back_to_Fight = CreateTrigger(  )
    call TriggerRegisterTimerExpireEventBJ( gg_trg_Back_to_Fight, udg_RestartTimer )
    call TriggerAddAction( gg_trg_Back_to_Fight, function Trig_Back_to_Fight_Actions )
endfunction

//===========================================================================
// Trigger: Set Creep Types
//===========================================================================
function Trig_Set_Creep_Types_Actions takes nothing returns nothing
    // Jail
    set udg_JailCreepType[1] = 'nkob'
    set udg_JailCreepType[2] = 'ndrj'
    set udg_JailCreepType[3] = 'nkog'
    set udg_JailCreepType[4] = 'nkot'
    set udg_JailCreepType[5] = 'nsln'
    set udg_JailCreepType[6] = 'nkol'
    set udg_JailCreepType[7] = 'nmgw'
    set udg_JailCreepType[8] = 'nmgr'
    set udg_JailCreepType[9] = 'nvde'
    set udg_JailCreepType[10] = 'nrvd'
    // Grounds
    set udg_GroundsCreepType[1] = 'nenc'
    set udg_GroundsCreepType[2] = 'ngrk'
    set udg_GroundsCreepType[3] = 'nenp'
    set udg_GroundsCreepType[4] = 'nele'
    set udg_GroundsCreepType[5] = 'nepl'
    set udg_GroundsCreepType[6] = 'ngst'
    set udg_GroundsCreepType[7] = 'ngst'
    set udg_GroundsCreepType[8] = 'nelb'
    set udg_GroundsCreepType[9] = 'nggr'
    set udg_GroundsCreepType[10] = 'nggr'
    // Shrine
    set udg_ShrineCreepType[1] = 'nhfp'
    set udg_ShrineCreepType[2] = 'ndrm'
    set udg_ShrineCreepType[3] = 'nhdc'
    set udg_ShrineCreepType[4] = 'ndrh'
    set udg_ShrineCreepType[5] = 'nhhr'
    set udg_ShrineCreepType[6] = 'ndrs'
    set udg_ShrineCreepType[7] = 'nfot'
    set udg_ShrineCreepType[8] = 'nfot'
    set udg_ShrineCreepType[9] = 'nvde'
    set udg_ShrineCreepType[10] = 'nfod'
    // City
    set udg_CityCreepType[1] = 'nban'
    set udg_CityCreepType[2] = 'nbrg'
    set udg_CityCreepType[3] = 'nrog'
    set udg_CityCreepType[4] = 'nass'
    set udg_CityCreepType[5] = 'nenf'
    set udg_CityCreepType[6] = 'nwzg'
    set udg_CityCreepType[7] = 'nbld'
    set udg_CityCreepType[8] = 'nbld'
    set udg_CityCreepType[9] = 'nwzd'
    set udg_CityCreepType[10] = 'nwzd'
endfunction

//===========================================================================
function InitTrig_Set_Creep_Types takes nothing returns nothing
    set gg_trg_Set_Creep_Types = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Set_Creep_Types, 4.00 )
    call TriggerAddAction( gg_trg_Set_Creep_Types, function Trig_Set_Creep_Types_Actions )
endfunction

//===========================================================================
// Trigger: Set Item Drops
//===========================================================================
function Trig_Set_Item_Drops_Actions takes nothing returns nothing
    set udg_RuneDropType[1] = 'rhe1'
    set udg_RuneDropType[2] = 'rhe1'
    set udg_RuneDropType[3] = 'rman'
    set udg_RuneDropType[4] = 'rman'
    set udg_RuneDropType[5] = 'manh'
    set udg_RuneDropType[6] = 'tdex'
    set udg_RuneDropType[7] = 'tint'
    set udg_RuneDropType[8] = 'tstr'
    set udg_RuneDropType[9] = 'tpow'
endfunction

//===========================================================================
function InitTrig_Set_Item_Drops takes nothing returns nothing
    set gg_trg_Set_Item_Drops = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Set_Item_Drops, 5.00 )
    call TriggerAddAction( gg_trg_Set_Item_Drops, function Trig_Set_Item_Drops_Actions )
endfunction

//===========================================================================
// Trigger: Make Creeps Startup
//===========================================================================
function Trig_Make_Creeps_Startup_Actions takes nothing returns nothing
    call EnableTrigger( gg_trg_Camp_Respawn )
endfunction

//===========================================================================
function InitTrig_Make_Creeps_Startup takes nothing returns nothing
    set gg_trg_Make_Creeps_Startup = CreateTrigger(  )
    call TriggerRegisterTimerEventSingle( gg_trg_Make_Creeps_Startup, 6.00 )
    call TriggerAddAction( gg_trg_Make_Creeps_Startup, function Trig_Make_Creeps_Startup_Actions )
endfunction

//===========================================================================
// Trigger: Drop Item
//===========================================================================
function Trig_Drop_Item_Func001C takes nothing returns boolean
    if ( not ( udg_RuneDropCount >= 6 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Drop_Item_Actions takes nothing returns nothing
    if ( Trig_Drop_Item_Func001C() ) then
        set udg_RuneDropCount = 0
        call CreateItemLoc( udg_RuneDropType[GetRandomInt(1, 9)], GetUnitLoc(GetTriggerUnit()) )
    else
        set udg_RuneDropCount = ( udg_RuneDropCount + 1 )
    endif
endfunction

//===========================================================================
function InitTrig_Drop_Item takes nothing returns nothing
    set gg_trg_Drop_Item = CreateTrigger(  )
    call TriggerRegisterPlayerUnitEventSimple( gg_trg_Drop_Item, Player(21), EVENT_PLAYER_UNIT_DEATH )
    call TriggerAddAction( gg_trg_Drop_Item, function Trig_Drop_Item_Actions )
endfunction

//===========================================================================
// Trigger: Camp Respawn
//===========================================================================
function Trig_Camp_Respawn_Actions takes nothing returns nothing
    call EnableTrigger( gg_trg_Jail1 )
    call EnableTrigger( gg_trg_Jail2 )
    call EnableTrigger( gg_trg_Jail3 )
    call EnableTrigger( gg_trg_Jail4 )
    call EnableTrigger( gg_trg_Jail5 )
    call EnableTrigger( gg_trg_Jail6 )
    call EnableTrigger( gg_trg_Jail7 )
    call EnableTrigger( gg_trg_City_Weak_1 )
    call EnableTrigger( gg_trg_City_Weak_2 )
    call EnableTrigger( gg_trg_City_Weak_3 )
    call EnableTrigger( gg_trg_City_5 )
    call EnableTrigger( gg_trg_City_6 )
    call EnableTrigger( gg_trg_City_2 )
    call EnableTrigger( gg_trg_City_4 )
    call EnableTrigger( gg_trg_City_3 )
    call EnableTrigger( gg_trg_ShrineWeak1 )
    call EnableTrigger( gg_trg_ShrineWeak2 )
    call EnableTrigger( gg_trg_ShrineWeak3 )
    call EnableTrigger( gg_trg_ShrineWeak4 )
    call EnableTrigger( gg_trg_ShrineWeak5 )
    call EnableTrigger( gg_trg_ShrineWeak6 )
    call EnableTrigger( gg_trg_Shrine3 )
    call EnableTrigger( gg_trg_Shrine2 )
    call EnableTrigger( gg_trg_Shrine1 )
    call EnableTrigger( gg_trg_Grounds2 )
    call EnableTrigger( gg_trg_Grounds3 )
    call EnableTrigger( gg_trg_Grounds4 )
    call EnableTrigger( gg_trg_Grounds5 )
    call EnableTrigger( gg_trg_Grounds1 )
    call DisableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Camp_Respawn takes nothing returns nothing
    set gg_trg_Camp_Respawn = CreateTrigger(  )
    call DisableTrigger( gg_trg_Camp_Respawn )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Camp_Respawn, 0.10 )
    call TriggerAddAction( gg_trg_Camp_Respawn, function Trig_Camp_Respawn_Actions )
endfunction

//===========================================================================
// Trigger: Jungle Farm Counter
//===========================================================================
function Trig_Jungle_Farm_Counter_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) == Player(21) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jungle_Farm_Counter_Actions takes nothing returns nothing
    set udg_JungleFarmCounter = ( udg_JungleFarmCounter + 1 )
endfunction

//===========================================================================
function InitTrig_Jungle_Farm_Counter takes nothing returns nothing
    set gg_trg_Jungle_Farm_Counter = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Jungle_Farm_Counter, EVENT_PLAYER_UNIT_DEATH )
    call TriggerAddCondition( gg_trg_Jungle_Farm_Counter, Condition( function Trig_Jungle_Farm_Counter_Conditions ) )
    call TriggerAddAction( gg_trg_Jungle_Farm_Counter, function Trig_Jungle_Farm_Counter_Actions )
endfunction

//===========================================================================
// Trigger: Team Farm Creeps
//===========================================================================
function Trig_Team_Farm_Creeps_Func003A takes nothing returns nothing
    call AdjustPlayerStateBJ( 150, GetEnumPlayer(), PLAYER_STATE_RESOURCE_GOLD )
    call AdjustPlayerStateBJ( 50, GetEnumPlayer(), PLAYER_STATE_RESOURCE_LUMBER )
endfunction

function Trig_Team_Farm_Creeps_Actions takes nothing returns nothing
    set udg_JungleFarmCounter = 0.00
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, "TRIGSTR_020" )
    call ForForce( GetPlayersByMapControl(MAP_CONTROL_USER), function Trig_Team_Farm_Creeps_Func003A )
    call EnableTrigger( gg_trg_Items )
endfunction

//===========================================================================
function InitTrig_Team_Farm_Creeps takes nothing returns nothing
    set gg_trg_Team_Farm_Creeps = CreateTrigger(  )
    call TriggerRegisterVariableEvent( gg_trg_Team_Farm_Creeps, "udg_JungleFarmCounter", EQUAL, 15.00 )
    call TriggerAddAction( gg_trg_Team_Farm_Creeps, function Trig_Team_Farm_Creeps_Actions )
endfunction

//===========================================================================
// Trigger: Jail1
//===========================================================================
function Trig_Jail1_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Jail1, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jail1_Actions takes nothing returns nothing
    if ( Trig_Jail1_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_JailCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Jail1), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Jail1 takes nothing returns nothing
    set gg_trg_Jail1 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Jail1 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Jail1, 0.10 )
    call TriggerAddAction( gg_trg_Jail1, function Trig_Jail1_Actions )
endfunction

//===========================================================================
// Trigger: Jail2
//===========================================================================
function Trig_Jail2_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Jail2, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jail2_Actions takes nothing returns nothing
    if ( Trig_Jail2_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_JailCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Jail2), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Jail2 takes nothing returns nothing
    set gg_trg_Jail2 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Jail2 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Jail2, 0.10 )
    call TriggerAddAction( gg_trg_Jail2, function Trig_Jail2_Actions )
endfunction

//===========================================================================
// Trigger: Jail3
//===========================================================================
function Trig_Jail3_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Jail3, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jail3_Actions takes nothing returns nothing
    if ( Trig_Jail3_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_JailCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Jail3), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Jail3 takes nothing returns nothing
    set gg_trg_Jail3 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Jail3 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Jail3, 0.10 )
    call TriggerAddAction( gg_trg_Jail3, function Trig_Jail3_Actions )
endfunction

//===========================================================================
// Trigger: Jail4
//===========================================================================
function Trig_Jail4_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Jail4, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jail4_Actions takes nothing returns nothing
    if ( Trig_Jail4_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_JailCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Jail4), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Jail4 takes nothing returns nothing
    set gg_trg_Jail4 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Jail4 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Jail4, 0.10 )
    call TriggerAddAction( gg_trg_Jail4, function Trig_Jail4_Actions )
endfunction

//===========================================================================
// Trigger: Jail5
//===========================================================================
function Trig_Jail5_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Jail5, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jail5_Actions takes nothing returns nothing
    if ( Trig_Jail5_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_JailCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Jail5), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Jail5 takes nothing returns nothing
    set gg_trg_Jail5 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Jail5 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Jail5, 0.10 )
    call TriggerAddAction( gg_trg_Jail5, function Trig_Jail5_Actions )
endfunction

//===========================================================================
// Trigger: Jail7
//===========================================================================
function Trig_Jail7_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Jail7, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jail7_Actions takes nothing returns nothing
    if ( Trig_Jail7_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_JailCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Jail7), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Jail7 takes nothing returns nothing
    set gg_trg_Jail7 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Jail7 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Jail7, 0.10 )
    call TriggerAddAction( gg_trg_Jail7, function Trig_Jail7_Actions )
endfunction

//===========================================================================
// Trigger: Jail6
//===========================================================================
function Trig_Jail6_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Jail_6, Player(21))) < 8 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jail6_Actions takes nothing returns nothing
    if ( Trig_Jail6_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_JailCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Jail_6), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Jail6 takes nothing returns nothing
    set gg_trg_Jail6 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Jail6 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Jail6, 0.10 )
    call TriggerAddAction( gg_trg_Jail6, function Trig_Jail6_Actions )
endfunction

//===========================================================================
// Trigger: Grounds1
//===========================================================================
function Trig_Grounds1_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Grounds1, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Grounds1_Actions takes nothing returns nothing
    if ( Trig_Grounds1_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_GroundsCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Grounds1), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Grounds1 takes nothing returns nothing
    set gg_trg_Grounds1 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Grounds1 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Grounds1, 0.10 )
    call TriggerAddAction( gg_trg_Grounds1, function Trig_Grounds1_Actions )
endfunction

//===========================================================================
// Trigger: Grounds2
//===========================================================================
function Trig_Grounds2_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Grounds2, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Grounds2_Actions takes nothing returns nothing
    if ( Trig_Grounds2_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_GroundsCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Grounds2), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Grounds2 takes nothing returns nothing
    set gg_trg_Grounds2 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Grounds2 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Grounds2, 0.10 )
    call TriggerAddAction( gg_trg_Grounds2, function Trig_Grounds2_Actions )
endfunction

//===========================================================================
// Trigger: Grounds3
//===========================================================================
function Trig_Grounds3_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Grounds3, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Grounds3_Actions takes nothing returns nothing
    if ( Trig_Grounds3_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_GroundsCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Grounds3), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Grounds3 takes nothing returns nothing
    set gg_trg_Grounds3 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Grounds3 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Grounds3, 0.10 )
    call TriggerAddAction( gg_trg_Grounds3, function Trig_Grounds3_Actions )
endfunction

//===========================================================================
// Trigger: Grounds4
//===========================================================================
function Trig_Grounds4_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Grounds4, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Grounds4_Actions takes nothing returns nothing
    if ( Trig_Grounds4_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_GroundsCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Grounds4), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Grounds4 takes nothing returns nothing
    set gg_trg_Grounds4 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Grounds4 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Grounds4, 0.10 )
    call TriggerAddAction( gg_trg_Grounds4, function Trig_Grounds4_Actions )
endfunction

//===========================================================================
// Trigger: Grounds5
//===========================================================================
function Trig_Grounds5_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Grounds5, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Grounds5_Actions takes nothing returns nothing
    if ( Trig_Grounds5_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_GroundsCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Grounds5), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Grounds5 takes nothing returns nothing
    set gg_trg_Grounds5 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Grounds5 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Grounds5, 0.10 )
    call TriggerAddAction( gg_trg_Grounds5, function Trig_Grounds5_Actions )
endfunction

//===========================================================================
// Trigger: Shrine3
//===========================================================================
function Trig_Shrine3_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Shrine3, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Shrine3_Actions takes nothing returns nothing
    if ( Trig_Shrine3_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Shrine3), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Shrine3 takes nothing returns nothing
    set gg_trg_Shrine3 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Shrine3 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Shrine3, 0.10 )
    call TriggerAddAction( gg_trg_Shrine3, function Trig_Shrine3_Actions )
endfunction

//===========================================================================
// Trigger: Shrine2
//===========================================================================
function Trig_Shrine2_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Shrine2, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Shrine2_Actions takes nothing returns nothing
    if ( Trig_Shrine2_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Shrine2), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Shrine2 takes nothing returns nothing
    set gg_trg_Shrine2 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Shrine2 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Shrine2, 0.10 )
    call TriggerAddAction( gg_trg_Shrine2, function Trig_Shrine2_Actions )
endfunction

//===========================================================================
// Trigger: Shrine1
//===========================================================================
function Trig_Shrine1_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_Shrine1, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Shrine1_Actions takes nothing returns nothing
    if ( Trig_Shrine1_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_Shrine1), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_Shrine1 takes nothing returns nothing
    set gg_trg_Shrine1 = CreateTrigger(  )
    call DisableTrigger( gg_trg_Shrine1 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Shrine1, 0.10 )
    call TriggerAddAction( gg_trg_Shrine1, function Trig_Shrine1_Actions )
endfunction

//===========================================================================
// Trigger: ShrineWeak1
//===========================================================================
function Trig_ShrineWeak1_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_ShrineWeak1, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_ShrineWeak1_Actions takes nothing returns nothing
    if ( Trig_ShrineWeak1_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_ShrineWeak1), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_ShrineWeak1 takes nothing returns nothing
    set gg_trg_ShrineWeak1 = CreateTrigger(  )
    call DisableTrigger( gg_trg_ShrineWeak1 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_ShrineWeak1, 0.10 )
    call TriggerAddAction( gg_trg_ShrineWeak1, function Trig_ShrineWeak1_Actions )
endfunction

//===========================================================================
// Trigger: ShrineWeak2
//===========================================================================
function Trig_ShrineWeak2_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_ShrineWeak2, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_ShrineWeak2_Actions takes nothing returns nothing
    if ( Trig_ShrineWeak2_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_ShrineWeak2), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_ShrineWeak2 takes nothing returns nothing
    set gg_trg_ShrineWeak2 = CreateTrigger(  )
    call DisableTrigger( gg_trg_ShrineWeak2 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_ShrineWeak2, 0.10 )
    call TriggerAddAction( gg_trg_ShrineWeak2, function Trig_ShrineWeak2_Actions )
endfunction

//===========================================================================
// Trigger: ShrineWeak3
//===========================================================================
function Trig_ShrineWeak3_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_ShrineWeak3, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_ShrineWeak3_Actions takes nothing returns nothing
    if ( Trig_ShrineWeak3_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_ShrineWeak3), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_ShrineWeak3 takes nothing returns nothing
    set gg_trg_ShrineWeak3 = CreateTrigger(  )
    call DisableTrigger( gg_trg_ShrineWeak3 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_ShrineWeak3, 0.10 )
    call TriggerAddAction( gg_trg_ShrineWeak3, function Trig_ShrineWeak3_Actions )
endfunction

//===========================================================================
// Trigger: ShrineWeak4
//===========================================================================
function Trig_ShrineWeak4_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_ShrineWeak4, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_ShrineWeak4_Actions takes nothing returns nothing
    if ( Trig_ShrineWeak4_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_ShrineWeak4), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_ShrineWeak4 takes nothing returns nothing
    set gg_trg_ShrineWeak4 = CreateTrigger(  )
    call DisableTrigger( gg_trg_ShrineWeak4 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_ShrineWeak4, 0.10 )
    call TriggerAddAction( gg_trg_ShrineWeak4, function Trig_ShrineWeak4_Actions )
endfunction

//===========================================================================
// Trigger: ShrineWeak5
//===========================================================================
function Trig_ShrineWeak5_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_ShrineWeak5, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_ShrineWeak5_Actions takes nothing returns nothing
    if ( Trig_ShrineWeak5_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_ShrineWeak5), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_ShrineWeak5 takes nothing returns nothing
    set gg_trg_ShrineWeak5 = CreateTrigger(  )
    call DisableTrigger( gg_trg_ShrineWeak5 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_ShrineWeak5, 0.10 )
    call TriggerAddAction( gg_trg_ShrineWeak5, function Trig_ShrineWeak5_Actions )
endfunction

//===========================================================================
// Trigger: ShrineWeak6
//===========================================================================
function Trig_ShrineWeak6_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_ShrineWeak6, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_ShrineWeak6_Actions takes nothing returns nothing
    if ( Trig_ShrineWeak6_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_ShrineCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_ShrineWeak6), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_ShrineWeak6 takes nothing returns nothing
    set gg_trg_ShrineWeak6 = CreateTrigger(  )
    call DisableTrigger( gg_trg_ShrineWeak6 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_ShrineWeak6, 0.10 )
    call TriggerAddAction( gg_trg_ShrineWeak6, function Trig_ShrineWeak6_Actions )
endfunction

//===========================================================================
// Trigger: City Weak 3
//===========================================================================
function Trig_City_Weak_3_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_Weak_3, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_Weak_3_Actions takes nothing returns nothing
    if ( Trig_City_Weak_3_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_Weak_3), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_Weak_3 takes nothing returns nothing
    set gg_trg_City_Weak_3 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_Weak_3 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_Weak_3, 0.10 )
    call TriggerAddAction( gg_trg_City_Weak_3, function Trig_City_Weak_3_Actions )
endfunction

//===========================================================================
// Trigger: City Weak 2
//===========================================================================
function Trig_City_Weak_2_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_Weak_2, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_Weak_2_Actions takes nothing returns nothing
    if ( Trig_City_Weak_2_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_Weak_2), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_Weak_2 takes nothing returns nothing
    set gg_trg_City_Weak_2 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_Weak_2 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_Weak_2, 0.10 )
    call TriggerAddAction( gg_trg_City_Weak_2, function Trig_City_Weak_2_Actions )
endfunction

//===========================================================================
// Trigger: City Weak 1
//===========================================================================
function Trig_City_Weak_1_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_Weak_1, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_Weak_1_Actions takes nothing returns nothing
    if ( Trig_City_Weak_1_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_Weak_1), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_Weak_1 takes nothing returns nothing
    set gg_trg_City_Weak_1 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_Weak_1 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_Weak_1, 0.10 )
    call TriggerAddAction( gg_trg_City_Weak_1, function Trig_City_Weak_1_Actions )
endfunction

//===========================================================================
// Trigger: City 6
//===========================================================================
function Trig_City_6_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_6, Player(21))) < 3 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_6_Actions takes nothing returns nothing
    if ( Trig_City_6_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_6), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_6 takes nothing returns nothing
    set gg_trg_City_6 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_6 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_6, 0.10 )
    call TriggerAddAction( gg_trg_City_6, function Trig_City_6_Actions )
endfunction

//===========================================================================
// Trigger: City 5
//===========================================================================
function Trig_City_5_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_5, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_5_Actions takes nothing returns nothing
    if ( Trig_City_5_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_5), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_5 takes nothing returns nothing
    set gg_trg_City_5 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_5 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_5, 0.10 )
    call TriggerAddAction( gg_trg_City_5, function Trig_City_5_Actions )
endfunction

//===========================================================================
// Trigger: City 4
//===========================================================================
function Trig_City_4_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_4, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_4_Actions takes nothing returns nothing
    if ( Trig_City_4_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_4), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_4 takes nothing returns nothing
    set gg_trg_City_4 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_4 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_4, 0.10 )
    call TriggerAddAction( gg_trg_City_4, function Trig_City_4_Actions )
endfunction

//===========================================================================
// Trigger: City 3
//===========================================================================
function Trig_City_3_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_3, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_3_Actions takes nothing returns nothing
    if ( Trig_City_3_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_3), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_3 takes nothing returns nothing
    set gg_trg_City_3 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_3 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_3, 0.10 )
    call TriggerAddAction( gg_trg_City_3, function Trig_City_3_Actions )
endfunction

//===========================================================================
// Trigger: City 2
//===========================================================================
function Trig_City_2_Func002C takes nothing returns boolean
    if ( not ( CountUnitsInGroup(GetUnitsInRectOfPlayer(gg_rct_City_2, Player(21))) < 5 ) ) then
        return false
    endif
    return true
endfunction

function Trig_City_2_Actions takes nothing returns nothing
    if ( Trig_City_2_Func002C() ) then
        call CreateNUnitsAtLoc( 1, udg_CityCreepType[GetRandomInt(1, udg_CreepLevel)], Player(21), GetRandomLocInRect(gg_rct_City_2), bj_UNIT_FACING )
    else
        call DisableTrigger( GetTriggeringTrigger() )
    endif
endfunction

//===========================================================================
function InitTrig_City_2 takes nothing returns nothing
    set gg_trg_City_2 = CreateTrigger(  )
    call DisableTrigger( gg_trg_City_2 )
    call TriggerRegisterTimerEventPeriodic( gg_trg_City_2, 0.10 )
    call TriggerAddAction( gg_trg_City_2, function Trig_City_2_Actions )
endfunction

//===========================================================================
// Trigger: Show Me Number
//===========================================================================
function Trig_Show_Me_Number_Actions takes nothing returns nothing
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, R2S(udg_BreakCountReal) )
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_UPDATED, R2S(udg_JungleFarmCounter) )
endfunction

//===========================================================================
function InitTrig_Show_Me_Number takes nothing returns nothing
    set gg_trg_Show_Me_Number = CreateTrigger(  )
    call TriggerRegisterPlayerChatEvent( gg_trg_Show_Me_Number, Player(0), "Show me Number", true )
    call TriggerAddAction( gg_trg_Show_Me_Number, function Trig_Show_Me_Number_Actions )
endfunction

//===========================================================================
// Trigger: Help Me
//===========================================================================
function Trig_Help_Me_Actions takes nothing returns nothing
    call CreateNUnitsAtLoc( 1, udg_Heroes[GetRandomInt(1, 24)], Player(0), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call ModifyHeroSkillPoints( GetLastCreatedUnit(), bj_MODIFYMETHOD_ADD, 1 )
    call CreateNUnitsAtLoc( 1, udg_Heroes[GetRandomInt(1, 24)], Player(0), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call ModifyHeroSkillPoints( GetLastCreatedUnit(), bj_MODIFYMETHOD_ADD, 1 )
    call CreateNUnitsAtLoc( 1, udg_Heroes[GetRandomInt(1, 24)], Player(0), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call ModifyHeroSkillPoints( GetLastCreatedUnit(), bj_MODIFYMETHOD_ADD, 1 )
endfunction

//===========================================================================
function InitTrig_Help_Me takes nothing returns nothing
    set gg_trg_Help_Me = CreateTrigger(  )
    call TriggerRegisterPlayerChatEvent( gg_trg_Help_Me, Player(0), "Help Me 112233", true )
    call TriggerAddAction( gg_trg_Help_Me, function Trig_Help_Me_Actions )
endfunction

//===========================================================================
// Trigger: Send Dudes
//===========================================================================
function Trig_Send_Dudes_Actions takes nothing returns nothing
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
    call CreateNUnitsAtLoc( 1, udg_UnitAlly[GetRandomInt(1, 15)], Player(23), GetRandomLocInRect(gg_rct_TheMiddle), bj_UNIT_FACING )
endfunction

//===========================================================================
function InitTrig_Send_Dudes takes nothing returns nothing
    set gg_trg_Send_Dudes = CreateTrigger(  )
    call TriggerRegisterPlayerChatEvent( gg_trg_Send_Dudes, Player(0), "Send Dudes 112233", true )
    call TriggerAddAction( gg_trg_Send_Dudes, function Trig_Send_Dudes_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Melee_Initialization(  )
    call InitTrig_LOSERS(  )
    call InitTrig_SetUnits(  )
    call InitTrig_Player_Startup(  )
    call InitTrig_Hero_Select(  )
    call InitTrig_Hero_Random(  )
    call InitTrig_Set_Up_Over(  )
    call InitTrig_ATTACK(  )
    call InitTrig_Boss_ATTACK(  )
    call InitTrig_ATTACKSend(  )
    call InitTrig_Creep_Level_Up(  )
    call InitTrig_Items(  )
    call InitTrig_Break_Counter(  )
    call InitTrig_Take_A_Break(  )
    call InitTrig_Back_to_Fight(  )
    call InitTrig_Set_Creep_Types(  )
    call InitTrig_Set_Item_Drops(  )
    call InitTrig_Make_Creeps_Startup(  )
    call InitTrig_Drop_Item(  )
    call InitTrig_Camp_Respawn(  )
    call InitTrig_Jungle_Farm_Counter(  )
    call InitTrig_Team_Farm_Creeps(  )
    call InitTrig_Jail1(  )
    call InitTrig_Jail2(  )
    call InitTrig_Jail3(  )
    call InitTrig_Jail4(  )
    call InitTrig_Jail5(  )
    call InitTrig_Jail7(  )
    call InitTrig_Jail6(  )
    call InitTrig_Grounds1(  )
    call InitTrig_Grounds2(  )
    call InitTrig_Grounds3(  )
    call InitTrig_Grounds4(  )
    call InitTrig_Grounds5(  )
    call InitTrig_Shrine3(  )
    call InitTrig_Shrine2(  )
    call InitTrig_Shrine1(  )
    call InitTrig_ShrineWeak1(  )
    call InitTrig_ShrineWeak2(  )
    call InitTrig_ShrineWeak3(  )
    call InitTrig_ShrineWeak4(  )
    call InitTrig_ShrineWeak5(  )
    call InitTrig_ShrineWeak6(  )
    call InitTrig_City_Weak_3(  )
    call InitTrig_City_Weak_2(  )
    call InitTrig_City_Weak_1(  )
    call InitTrig_City_6(  )
    call InitTrig_City_5(  )
    call InitTrig_City_4(  )
    call InitTrig_City_3(  )
    call InitTrig_City_2(  )
    call InitTrig_Show_Me_Number(  )
    call InitTrig_Help_Me(  )
    call InitTrig_Send_Dudes(  )
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute( gg_trg_Melee_Initialization )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), true )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(1), true )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )

    // Player 2
    call SetPlayerStartLocation( Player(2), 2 )
    call ForcePlayerStartLocation( Player(2), 2 )
    call SetPlayerColor( Player(2), ConvertPlayerColor(2) )
    call SetPlayerRacePreference( Player(2), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(2), true )
    call SetPlayerController( Player(2), MAP_CONTROL_USER )

    // Player 3
    call SetPlayerStartLocation( Player(3), 3 )
    call ForcePlayerStartLocation( Player(3), 3 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(3), true )
    call SetPlayerController( Player(3), MAP_CONTROL_USER )

    // Player 21
    call SetPlayerStartLocation( Player(21), 4 )
    call SetPlayerColor( Player(21), ConvertPlayerColor(21) )
    call SetPlayerRacePreference( Player(21), RACE_PREF_ORC )
    call SetPlayerRaceSelectable( Player(21), true )
    call SetPlayerController( Player(21), MAP_CONTROL_COMPUTER )

    // Player 22
    call SetPlayerStartLocation( Player(22), 5 )
    call SetPlayerColor( Player(22), ConvertPlayerColor(22) )
    call SetPlayerRacePreference( Player(22), RACE_PREF_UNDEAD )
    call SetPlayerRaceSelectable( Player(22), true )
    call SetPlayerController( Player(22), MAP_CONTROL_COMPUTER )

    // Player 23
    call SetPlayerStartLocation( Player(23), 6 )
    call SetPlayerColor( Player(23), ConvertPlayerColor(23) )
    call SetPlayerRacePreference( Player(23), RACE_PREF_NIGHTELF )
    call SetPlayerRaceSelectable( Player(23), true )
    call SetPlayerController( Player(23), MAP_CONTROL_COMPUTER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerTeam( Player(1), 0 )
    call SetPlayerTeam( Player(2), 0 )
    call SetPlayerTeam( Player(3), 0 )
    call SetPlayerTeam( Player(23), 0 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(23), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(23), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(23), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(23), true )
    call SetPlayerAllianceStateAllyBJ( Player(23), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(23), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(23), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(23), Player(3), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(23), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(23), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(23), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(23), true )
    call SetPlayerAllianceStateVisionBJ( Player(23), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(23), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(23), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(23), Player(3), true )

    // Force: TRIGSTR_011
    call SetPlayerTeam( Player(21), 1 )
    call SetPlayerTeam( Player(22), 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(21), Player(22), true )
    call SetPlayerAllianceStateAllyBJ( Player(22), Player(21), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(21), Player(22), true )
    call SetPlayerAllianceStateVisionBJ( Player(22), Player(21), true )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 0, 3 )
    call SetStartLocPrio( 0, 0, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 1, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 2, 3, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 1, 3 )
    call SetStartLocPrio( 1, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 1, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 2, 3, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 2, 3 )
    call SetStartLocPrio( 2, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 2, 3, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 3, 3 )
    call SetStartLocPrio( 3, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 2, 2, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 4, 1 )
    call SetStartLocPrio( 4, 0, 2, MAP_LOC_PRIO_LOW )

    call SetEnemyStartLocPrioCount( 4, 2 )
    call SetEnemyStartLocPrio( 4, 0, 1, MAP_LOC_PRIO_HIGH )
    call SetEnemyStartLocPrio( 4, 1, 2, MAP_LOC_PRIO_LOW )

    call SetStartLocPrioCount( 5, 6 )
    call SetStartLocPrio( 5, 0, 0, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 5, 1, 1, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 5, 2, 2, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 5, 3, 3, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 5, 4, 6, MAP_LOC_PRIO_LOW )

    call SetEnemyStartLocPrioCount( 5, 6 )
    call SetEnemyStartLocPrio( 5, 0, 0, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 5, 1, 1, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 5, 2, 2, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 5, 3, 3, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 5, 4, 6, MAP_LOC_PRIO_LOW )

    call SetStartLocPrioCount( 6, 5 )
    call SetStartLocPrio( 6, 0, 0, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 6, 1, 1, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 6, 2, 2, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 6, 3, 3, MAP_LOC_PRIO_LOW )
    call SetStartLocPrio( 6, 4, 4, MAP_LOC_PRIO_HIGH )

    call SetEnemyStartLocPrioCount( 6, 4 )
    call SetEnemyStartLocPrio( 6, 0, 0, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 6, 1, 1, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 6, 2, 2, MAP_LOC_PRIO_LOW )
    call SetEnemyStartLocPrio( 6, 3, 3, MAP_LOC_PRIO_LOW )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -8192.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -8192.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 8192.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 8192.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -8192.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 8192.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 8192.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -8192.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl", "Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "DalaranDay" )
    call SetAmbientNightSound( "DalaranNight" )
    call SetMapMusic( "Music", true, 0 )
    call CreateRegions(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )
    call RunInitializationTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_013" )
    call SetMapDescription( "TRIGSTR_015" )
    call SetPlayers( 7 )
    call SetTeams( 7 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )

    call DefineStartLocation( 0, 64.0, -7680.0 )
    call DefineStartLocation( 1, 64.0, -7680.0 )
    call DefineStartLocation( 2, 64.0, -7680.0 )
    call DefineStartLocation( 3, 64.0, -7680.0 )
    call DefineStartLocation( 4, -3072.0, -7040.0 )
    call DefineStartLocation( 5, 6336.0, 6656.0 )
    call DefineStartLocation( 6, 0.0, -512.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call InitCustomTeams(  )
    call InitAllyPriorities(  )
endfunction

